version: '3'

services:
    keycloak:
        image: quay.io/keycloak/keycloak:21.1
        command:
            - start-dev
            - --import-realm
            - --health-enabled=true
        volumes:
            - ./imports/realm-export.json:/opt/keycloak/data/import/realm.json
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        #healthcheck:
        #    test: curl --fail http://localhost:8080/health/ready || exit 1
        #    interval: 5s
        #    timeout: 2s
        #    retries: 15
        ports:
            - "8085:8080"