version: '3.3'

volumes:
    postgres_data:
        driver: local

services:
    keycloak:
        image: quay.io/keycloak/keycloak:21.1
        command:
            - start-dev
            - --import-realm
        volumes:
            - ./imports/realm-export.json:/opt/keycloak/data/import/realm.json
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "8085:8080"