# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [ push, pull_request ]

jobs:
    properties:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -f spring-boot-properties clean verify

    rest-services:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -f spring-boot-rest-services clean verify

    // TODO see https://github.com/whelk-io/maven-settings-xml-action
    #docker-using-maven-plugin:
    #    runs-on: ubuntu-latest
#
    #    strategy:
    #        matrix:
    #            java: [ 17 ]
#
    #    name: Java ${{ matrix.java }} compile
#
    #    steps:
    #        -  name: Check out code into the Go module directory
    #           uses: actions/checkout@v2
#
    #        - name: Login to DockerHub
    #          uses: docker/login-action@v1
    #          with:
    #              username: ${{ secrets.DOCKER_USERNAME }}
    #              password: ${{ secrets.DOCKER_PASSWORD }}
#
    #        - name: Setup java ${{ matrix.java }}
    #          uses: actions/setup-java@v1
    #          with:
    #              java-version: ${{ matrix.java }}
    #        - run: mvn -f spring-boot-in-docker/spring-boot-in-docker-using-maven-plugin clean verify

    postgres:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-postgres clean verify

    mongodb:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-mongodb clean verify

    elasticsearch:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-elasticsearch clean verify

    rabbitmq:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-rabbitmq clean verify

    keycloak-service-1:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-keycloak/spring-boot-keycloak-service-1 clean verify

    keycloak-service-2:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        name: Java ${{ matrix.java }} compile

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-keycloak/spring-boot-keycloak-service-2 clean verify
