name: spring-boot-keycloak

on:
    push:
        paths:
            - 'spring-boot-keycloak/**'
    pull_request:
        paths:
            - 'spring-boot-keycloak/**'

jobs:
    keycloak-service-1:
        name: Build spring boot using keycloak (service 1) with java version ${{ matrix.java }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-keycloak/spring-boot-keycloak-service-1 clean verify

    keycloak-service-2:
        name: Build spring boot using keycloak (service 2) with java version ${{ matrix.java }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17 ]

        steps:
            -   uses: actions/checkout@v1
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-keycloak/spring-boot-keycloak-service-2 clean verify
