name: spring-boot-postgres

on:
    push:
        paths:
            - 'spring-boot-postgres-java/**'
            - '.github/workflows/spring-boot-postgres.yml'
    pull_request:
        paths:
            - 'spring-boot-postgres-java/**'
            - '.github/workflows/spring-boot-postgres.yml'

jobs:
    postgres:
        name: Build spring boot using postres with java version ${{ matrix.java }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17,18 ]

        steps:
            -   uses: actions/checkout@v3
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-postgres clean verify